annotations:
  truecharts.org/category: security
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: incubator
apiVersion: v2
appVersion: 1.32.2
dependencies:
  - name: common
    version: 25.1.5
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: High-performance, resource-efficient Minecraft reverse proxy with robust multi-protocol version support.
home: https://truecharts.org/charts/incubator/minecraft-gate
icon: https://truecharts.org/img/hotlink-ok/chart-icons/minecraft-gate.webp
keywords:
  - minecraft-gate
  - proxy
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: minecraft-gate
sources:
  - https://ghcr.io/minekube/gate
  - https://github.com/minekube/gate
  - https://github.com/truecharts/charts/tree/master/charts/incubator/minecraft-gate
type: application
version: 0.0.1