image:
  repository: docker.io/itzg/mc-router
  pullPolicy: IfNotPresent
  tag: 1.23.0@sha256:e8c8d56a1244209fffc1f8ec35eca89631d0bfdfb55b375b04b8d2f27d55afb3
service:
  main:
    ports:
      main:
        port: 25565
  api:
    enabled: true
    ports:
      api:
        enabled: true
        port: 25564

mcrouter:
  default-server: vanilla:25565
  mappings:
    vanilla.example.com: vanilla:25565
    forge.example.com: forge:25565

configmap:
  config:
    enabled: true
    data:
      config.json:
        {{ toJson .Values.mcrouter }}

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
          env:
            API_BINDING: ":{{ .Values.service.main.ports.main.port }}"
            PORT: "{{ .Values.service.minecraft.ports.minecraft.port }}"
            ROUTES_CONFIG: "{{ .Values.persistence.config.mountPath }}"

persistence:
  config:
    enabled: true
    type: configmap
    objectName: config
    mountPath: /config/config.json
    subPath: config.json

portal:
  open:
    enabled: false
